// src/foodData.js
// Kanka bu dosya senin uygulamanın tüm market deposudur. İstediğin kadar büyütebilirsin!
// Değerler yaklaşık olarak 100g başına protein (P) ve yağ (F) gramıdır.

const foodData = {
    Dairy_and_Eggs: [
        { id: 'm1', name: 'Milk', protein: 3.4, fat: 3.6, vitamin: 'D, B12, Ca' },
        { id: 'm2', name: 'Yogurt', protein: 10, fat: 4, vitamin: 'B2, Ca' },
        { id: 'm3', name: 'Feta Cheese', protein: 14, fat: 21, vitamin: 'A, B12' },
        { id: 'm4', name: 'Cheddar', protein: 25, fat: 33, vitamin: 'A, B2' },
        { id: 'm5', name: 'Cottage Cheese', protein: 11, fat: 4, vitamin: 'B12, Se' },
        { id: 'm6', name: 'Butter', protein: 1, fat: 81, vitamin: 'A, E' },
        { id: 'm7', name: 'Kefir', protein: 4, fat: 1, vitamin: 'B12, Ca' },
        { id: 'm8', name: 'Eggs', protein: 13, fat: 11, vitamin: 'B12, D, Choline' },
        { id: 'm9', name: 'Mozzarella', protein: 22, fat: 22, vitamin: 'B12, Ca' },
        { id: 'm10', name: 'Parmesan', protein: 38, fat: 29, vitamin: 'A, B12, Ca' },
        { id: 'm11', name: 'Gouda', protein: 25, fat: 27, vitamin: 'B12, Zinc' },
        { id: 'm12', name: 'Cream Cheese', protein: 6, fat: 34, vitamin: 'A' },
        { id: 'm13', name: 'Ricotta', protein: 11, fat: 13, vitamin: 'A, B12' },
        { id: 'm14', name: 'Sour Cream', protein: 2.4, fat: 20, vitamin: 'A, Ca' },
        { id: 'm15', name: 'Greek Yogurt', protein: 10, fat: 5, vitamin: 'B12, Ca' },
        { id: 'm16', name: 'Skyr', protein: 11, fat: 0.2, vitamin: 'B12, Ca' },
        { id: 'm17', name: 'Quark', protein: 12, fat: 0.3, vitamin: 'B12, Ca' },
        { id: 'm18', name: 'Goat Cheese', protein: 22, fat: 30, vitamin: 'A, B2' },
        { id: 'm19', name: 'Halloumi', protein: 22, fat: 26, vitamin: 'Ca, B12' },
        { id: 'm20', name: 'Labneh', protein: 8, fat: 10, vitamin: 'Ca, B12' }
    ],
    Meat_and_Poultry: [
        { id: 'e1', name: 'Chicken Breast', protein: 31, fat: 3.6, vitamin: 'B6, B3' },
        { id: 'e2', name: 'Beef', protein: 26, fat: 15, vitamin: 'Iron, B12' },
        { id: 'e3', name: 'Turkey Breast', protein: 29, fat: 1.5, vitamin: 'B6, B12' },
        { id: 'e4', name: 'Lamb', protein: 25, fat: 21, vitamin: 'B12, Zinc' },
        { id: 'e5', name: 'Pork Chop', protein: 25, fat: 14, vitamin: 'B1, B6' },
        { id: 'e6', name: 'Duck', protein: 19, fat: 28, vitamin: 'B5, Iron' },
        { id: 'e7', name: 'Veal', protein: 24, fat: 3, vitamin: 'B3, B12' },
        { id: 'e8', name: 'Chicken Thigh', protein: 24, fat: 8, vitamin: 'B5, Zinc' },
        { id: 'e9', name: 'Minced Beef', protein: 26, fat: 20, vitamin: 'B12, Iron' },
        { id: 'e10', name: 'Chicken Wings', protein: 22, fat: 12, vitamin: 'B6, B3' },
        { id: 'e11', name: 'Chicken Drumstick', protein: 24, fat: 9, vitamin: 'B6, B12' },
        { id: 'e12', name: 'Beef Steak', protein: 27, fat: 17, vitamin: 'Iron, Zinc' },
        { id: 'e13', name: 'Beef Liver', protein: 26, fat: 4, vitamin: 'A, B12, Iron' },
        { id: 'e14', name: 'Ground Turkey', protein: 27, fat: 8, vitamin: 'B6, B3' },
        { id: 'e15', name: 'Sucuk', protein: 19, fat: 40, vitamin: 'B12, Iron' },
        { id: 'e16', name: 'Quail', protein: 22, fat: 12, vitamin: 'B3, Iron' }
    ],
    Seafood: [
        { id: 'f1', name: 'Salmon', protein: 20, fat: 13, vitamin: 'D, Om-3' },
        { id: 'f2', name: 'Shrimp', protein: 24, fat: 0.3, vitamin: 'B12, Se' },
        { id: 'f3', name: 'Tuna', protein: 28, fat: 1, vitamin: 'D, B12' },
        { id: 'f4', name: 'Cod', protein: 18, fat: 0.7, vitamin: 'B12, Iodine' },
        { id: 'f5', name: 'Mackerel', protein: 19, fat: 14, vitamin: 'D, B12' },
        { id: 'f6', name: 'Sardines', protein: 25, fat: 11, vitamin: 'D, Ca' },
        { id: 'f7', name: 'Scallops', protein: 21, fat: 0.8, vitamin: 'B12, Mg' },
        { id: 'f8', name: 'Crab', protein: 19, fat: 1.5, vitamin: 'B12, Zinc' },
        { id: 'f9', name: 'Lobster', protein: 19, fat: 0.9, vitamin: 'Copper, Se' },
        { id: 'f10', name: 'Trout', protein: 20, fat: 6, vitamin: 'D, B12' },
        { id: 'f11', name: 'Sea Bass', protein: 18, fat: 2.5, vitamin: 'D, B12' },
        { id: 'f12', name: 'Sea Bream', protein: 20, fat: 3, vitamin: 'D, B12' },
        { id: 'f13', name: 'Anchovy', protein: 20, fat: 4.8, vitamin: 'D, Om-3' },
        { id: 'f14', name: 'Octopus', protein: 15, fat: 1, vitamin: 'B12, Iron' },
        { id: 'f15', name: 'Squid', protein: 16, fat: 1.4, vitamin: 'B12, Se' },
        { id: 'f16', name: 'Mussels', protein: 12, fat: 2.2, vitamin: 'B12, Iron' }
    ],
    Vegetables: [
        { id: 's1', name: 'Spinach', protein: 2.9, fat: 0.4, vitamin: 'K, A, C' },
        { id: 's2', name: 'Broccoli', protein: 2.8, fat: 0.4, vitamin: 'C, K' },
        { id: 's3', name: 'Carrot', protein: 0.9, fat: 0.2, vitamin: 'A, K1' },
        { id: 's4', name: 'Garlic', protein: 6.4, fat: 0.5, vitamin: 'C, B6' },
        { id: 's5', name: 'Onion', protein: 1.1, fat: 0.1, vitamin: 'C, B6' },
        { id: 's6', name: 'Tomato', protein: 0.9, fat: 0.2, vitamin: 'C, K' },
        { id: 's7', name: 'Cucumber', protein: 0.6, fat: 0.1, vitamin: 'K, C' },
        { id: 's8', name: 'Bell Pepper', protein: 1, fat: 0.2, vitamin: 'C, A' },
        { id: 's9', name: 'Zucchini', protein: 1.2, fat: 0.3, vitamin: 'C, B6' },
        { id: 's10', name: 'Asparagus', protein: 2.2, fat: 0.1, vitamin: 'K, B9' },
        { id: 's11', name: 'Cabbage', protein: 1.3, fat: 0.1, vitamin: 'K, C' },
        { id: 's12', name: 'Cauliflower', protein: 1.9, fat: 0.3, vitamin: 'C, K' },
        { id: 's13', name: 'Celery', protein: 0.7, fat: 0.2, vitamin: 'K, A' },
        { id: 's14', name: 'Eggplant', protein: 1, fat: 0.2, vitamin: 'B1, B6' },
        { id: 's15', name: 'Kale', protein: 4.3, fat: 1.5, vitamin: 'A, K, C' },
        { id: 's16', name: 'Lettuce', protein: 1.4, fat: 0.2, vitamin: 'K, A' },
        { id: 's17', name: 'Mushroom', protein: 3.1, fat: 0.3, vitamin: 'D, B2' },
        { id: 's18', name: 'Potato', protein: 2, fat: 0.1, vitamin: 'C, B6' },
        { id: 's19', name: 'Sweet Potato', protein: 1.6, fat: 0.1, vitamin: 'A, C' },
        { id: 's20', name: 'Brussels Sprouts', protein: 3.4, fat: 0.3, vitamin: 'K, C' },
        { id: 's21', name: 'Pumpkin', protein: 1, fat: 0.1, vitamin: 'A, C' },
        { id: 's22', name: 'Beetroot', protein: 1.6, fat: 0.2, vitamin: 'B9, Mn' },
        { id: 's23', name: 'Radish', protein: 0.7, fat: 0.1, vitamin: 'C, B9' },
        { id: 's24', name: 'Green Beans', protein: 1.8, fat: 0.2, vitamin: 'C, K' },
        { id: 's25', name: 'Okra', protein: 1.9, fat: 0.2, vitamin: 'C, K, B9' },
        { id: 's26', name: 'Artichoke', protein: 3.3, fat: 0.2, vitamin: 'C, K, B9' },
        { id: 's27', name: 'Leek', protein: 1.5, fat: 0.3, vitamin: 'K, A' },
        { id: 's28', name: 'Arugula', protein: 2.6, fat: 0.7, vitamin: 'K, A, C' }
    ],
    Fruits: [
        { id: 'fr1', name: 'Apple', protein: 0.3, fat: 0.2, vitamin: 'C, Fiber' },
        { id: 'fr2', name: 'Banana', protein: 1.1, fat: 0.3, vitamin: 'B6, C' },
        { id: 'fr3', name: 'Orange', protein: 0.9, fat: 0.1, vitamin: 'C, B9' },
        { id: 'fr4', name: 'Strawberry', protein: 0.7, fat: 0.3, vitamin: 'C, B9' },
        { id: 'fr5', name: 'Avocado', protein: 2, fat: 15, vitamin: 'K, E, C' },
        { id: 'fr6', name: 'Blueberry', protein: 0.7, fat: 0.3, vitamin: 'C, K' },
        { id: 'fr7', name: 'Blackberry', protein: 1.4, fat: 0.5, vitamin: 'C, K' },
        { id: 'fr8', name: 'Mango', protein: 0.8, fat: 0.4, vitamin: 'C, A' },
        { id: 'fr9', name: 'Pineapple', protein: 0.5, fat: 0.1, vitamin: 'C, Mn' },
        { id: 'fr10', name: 'Watermelon', protein: 0.6, fat: 0.2, vitamin: 'C, A' },
        { id: 'fr11', name: 'Peach', protein: 0.9, fat: 0.3, vitamin: 'C, A' },
        { id: 'fr12', name: 'Pear', protein: 0.4, fat: 0.1, vitamin: 'C, K' },
        { id: 'fr13', name: 'Cherry', protein: 1, fat: 0.3, vitamin: 'C, K' },
        { id: 'fr14', name: 'Grape', protein: 0.6, fat: 0.2, vitamin: 'C, K' },
        { id: 'fr15', name: 'Kiwi', protein: 1.1, fat: 0.5, vitamin: 'C, K' },
        { id: 'fr16', name: 'Lemon', protein: 1.1, fat: 0.3, vitamin: 'C' },
        { id: 'fr17', name: 'Pomegranate', protein: 1.7, fat: 1.2, vitamin: 'C, K' },
        { id: 'fr18', name: 'Fig', protein: 0.8, fat: 0.3, vitamin: 'B6, K' },
        { id: 'fr19', name: 'Apricot', protein: 1.4, fat: 0.4, vitamin: 'A, C' },
        { id: 'fr20', name: 'Plum', protein: 0.7, fat: 0.3, vitamin: 'C, K' },
        { id: 'fr21', name: 'Grapefruit', protein: 0.8, fat: 0.1, vitamin: 'C, A' },
        { id: 'fr22', name: 'Melon', protein: 0.8, fat: 0.2, vitamin: 'C, A' },
        { id: 'fr23', name: 'Dates', protein: 1.8, fat: 0.2, vitamin: 'B6, K' },
        { id: 'fr24', name: 'Raspberry', protein: 1.2, fat: 0.7, vitamin: 'C, K' }
    ],
    Nuts_and_Seeds: [
        { id: 'k1', name: 'Walnut', protein: 15, fat: 65, vitamin: 'E, B6' },
        { id: 'k2', name: 'Almond', protein: 21, fat: 49, vitamin: 'E, Mg' },
        { id: 'k3', name: 'Chia Seeds', protein: 17, fat: 31, vitamin: 'B1, Mg' },
        { id: 'k4', name: 'Peanut', protein: 26, fat: 49, vitamin: 'B3, B9' },
        { id: 'k5', name: 'Pistachio', protein: 20, fat: 45, vitamin: 'B6, B1' },
        { id: 'k6', name: 'Cashew', protein: 18, fat: 44, vitamin: 'K, Zinc' },
        { id: 'k7', name: 'Hazelnut', protein: 15, fat: 61, vitamin: 'E, Cu' },
        { id: 'k8', name: 'Pecan', protein: 9, fat: 72, vitamin: 'B1, Zinc' },
        { id: 'k9', name: 'Sunflower Seeds', protein: 21, fat: 51, vitamin: 'E, B1' },
        { id: 'k10', name: 'Pumpkin Seeds', protein: 19, fat: 49, vitamin: 'K, Zinc' },
        { id: 'k11', name: 'Flaxseed', protein: 18, fat: 42, vitamin: 'B1, Cu' },
        { id: 'k12', name: 'Brazil Nuts', protein: 14, fat: 67, vitamin: 'Se, E' },
        { id: 'k13', name: 'Macadamia', protein: 8, fat: 76, vitamin: 'B1, Mn' },
        { id: 'k14', name: 'Sesame Seeds', protein: 18, fat: 50, vitamin: 'Ca, B1' }
    ],
    Legumes: [
        { id: 'b1', name: 'Red Lentils', protein: 25, fat: 1.1, vitamin: 'B9, Iron' },
        { id: 'b2', name: 'Chickpeas', protein: 19, fat: 6, vitamin: 'B6, Mg' },
        { id: 'b3', name: 'Soybeans', protein: 36, fat: 20, vitamin: 'K1, B9' },
        { id: 'b4', name: 'Black Beans', protein: 21, fat: 0.9, vitamin: 'B1, B9' },
        { id: 'b5', name: 'Kidney Beans', protein: 24, fat: 0.8, vitamin: 'K1, Iron' },
        { id: 'b6', name: 'Green Peas', protein: 5, fat: 0.4, vitamin: 'A, C, K' },
        { id: 'b7', name: 'Pinto Beans', protein: 21, fat: 1.2, vitamin: 'B1, B9' },
        { id: 'b8', name: 'Edamame', protein: 11, fat: 5, vitamin: 'K, B9' },
        { id: 'b9', name: 'White Beans', protein: 21, fat: 0.9, vitamin: 'B9, Iron' },
        { id: 'b10', name: 'Fava Beans', protein: 26, fat: 1.5, vitamin: 'B9, B1' },
        { id: 'b11', name: 'Mung Beans', protein: 24, fat: 1.2, vitamin: 'B9, Mg' }
    ],
    Grains_and_Carbs: [
        { id: 't1', name: 'Rice', protein: 2.7, fat: 0.3, vitamin: 'B1, B6' },
        { id: 't2', name: 'Oats', protein: 17, fat: 6.9, vitamin: 'B1, B5' },
        { id: 't3', name: 'Quinoa', protein: 14, fat: 6, vitamin: 'B6, B9' },
        { id: 't4', name: 'Whole Wheat Bread', protein: 13, fat: 3.4, vitamin: 'B1, B3' },
        { id: 't5', name: 'Pasta', protein: 5.8, fat: 0.9, vitamin: 'B1, B9' },
        { id: 't6', name: 'Barley', protein: 12, fat: 1.2, vitamin: 'B1, B3' },
        { id: 't7', name: 'Buckwheat', protein: 13, fat: 3.4, vitamin: 'B3, Mg' },
        { id: 't8', name: 'Bulgur', protein: 12, fat: 1.3, vitamin: 'B3, Mn' },
        { id: 't9', name: 'Couscous', protein: 3.8, fat: 0.2, vitamin: 'B3, Se' },
        { id: 't10', name: 'Corn', protein: 3.3, fat: 1.5, vitamin: 'B5, B9' },
        { id: 't11', name: 'Brown Rice', protein: 7.5, fat: 2.7, vitamin: 'B1, Mg' },
        { id: 't12', name: 'Rye Bread', protein: 9, fat: 3.3, vitamin: 'B1, B3' },
        { id: 't13', name: 'Tortilla', protein: 8, fat: 7, vitamin: 'B1, B3' },
        { id: 't14', name: 'Noodles', protein: 7, fat: 1, vitamin: 'B1, B9' }
    ],
    Oils_and_Fats: [
        { id: 'o1', name: 'Olive Oil', protein: 0, fat: 100, vitamin: 'E, K' },
        { id: 'o2', name: 'Coconut Oil', protein: 0, fat: 100, vitamin: 'E' },
        { id: 'o3', name: 'Avocado Oil', protein: 0, fat: 100, vitamin: 'E' },
        { id: 'o4', name: 'Sesame Oil', protein: 0, fat: 100, vitamin: 'E, K' },
        { id: 'o5', name: 'Tahini', protein: 17, fat: 54, vitamin: 'B1, Ca' },
        { id: 'o6', name: 'Peanut Butter', protein: 25, fat: 50, vitamin: 'B3, E' },
        { id: 'o7', name: 'Ghee', protein: 0, fat: 100, vitamin: 'A, E' }
    ],
    Herbs_and_Spices: [
        { id: 'h1', name: 'Basil', protein: 3.2, fat: 0.6, vitamin: 'K, A' },
        { id: 'h2', name: 'Mint', protein: 3.8, fat: 0.9, vitamin: 'A, C' },
        { id: 'h3', name: 'Parsley', protein: 3, fat: 0.8, vitamin: 'K, C, A' },
        { id: 'h4', name: 'Dill', protein: 3.5, fat: 1.1, vitamin: 'C, A' },
        { id: 'h5', name: 'Oregano', protein: 9, fat: 4.3, vitamin: 'K, E' },
        { id: 'h6', name: 'Rosemary', protein: 3.3, fat: 5.9, vitamin: 'A, C' },
        { id: 'h7', name: 'Thyme', protein: 5.6, fat: 1.7, vitamin: 'C, A' },
        { id: 'h8', name: 'Cumin', protein: 18, fat: 22, vitamin: 'Iron, Mn' },
        { id: 'h9', name: 'Paprika', protein: 14, fat: 13, vitamin: 'A, E' },
        { id: 'h10', name: 'Turmeric', protein: 8, fat: 10, vitamin: 'Mn, Iron' },
        { id: 'h11', name: 'Ginger', protein: 1.8, fat: 0.8, vitamin: 'B6, Mg' },
        { id: 'h12', name: 'Cinnamon', protein: 4, fat: 1.2, vitamin: 'Mn, Ca' },
        { id: 'h13', name: 'Black Pepper', protein: 10, fat: 3.3, vitamin: 'Mn, K' }
    ],
    Beverages: [
        { id: 'bv1', name: 'Green Tea', protein: 0, fat: 0, vitamin: 'Antioxidants' },
        { id: 'bv2', name: 'Black Tea', protein: 0, fat: 0, vitamin: 'Antioxidants' },
        { id: 'bv3', name: 'Coffee', protein: 0.1, fat: 0, vitamin: 'B3, Mg' },
        { id: 'bv4', name: 'Ayran', protein: 1.7, fat: 1.5, vitamin: 'Ca, B12' },
        { id: 'bv5', name: 'Kombucha', protein: 0, fat: 0, vitamin: 'B12, Probiotics' },
        { id: 'bv6', name: 'Orange Juice', protein: 0.7, fat: 0.2, vitamin: 'C, B9' },
        { id: 'bv7', name: 'Coconut Water', protein: 0.7, fat: 0.2, vitamin: 'K, Mg' },
        { id: 'bv8', name: 'Mineral Water', protein: 0, fat: 0, vitamin: 'Ca, Mg' }
    ],
    Sweets_and_Extras: [
        { id: 'sw1', name: 'Honey', protein: 0.3, fat: 0, vitamin: 'Antioxidants' },
        { id: 'sw2', name: 'Dark Chocolate', protein: 7.8, fat: 43, vitamin: 'Iron, Mg' },
        { id: 'sw3', name: 'Maple Syrup', protein: 0, fat: 0.1, vitamin: 'Mn, B2' },
        { id: 'sw4', name: 'Granola', protein: 10, fat: 15, vitamin: 'B1, E' },
        { id: 'sw5', name: 'Protein Bar', protein: 30, fat: 10, vitamin: 'B Vitamins' },
        { id: 'sw6', name: 'Popcorn', protein: 11, fat: 4.5, vitamin: 'B3, Mg' }
    ]
};

export default foodData;
